apiVersion: ephemeral.hoaqim.dev/v1alpha1
kind: EphemeralEnvironment
metadata:
  labels:
    app.kubernetes.io/name: ee-operator
    app.kubernetes.io/managed-by: kustomize
  name: ephemeralenvironment-sample
spec:
  ttl: "5m"
  template:
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
